---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # 1. Security and Credentials checks
      - id: check-added-large-files
      - id: detect-aws-credentials
      - id: no-commit-to-branch

      # 2. Formatting and Clean Code
      - id: trailing-whitespace
      - id: pretty-format-json
        args: [--autofix, --no-sort-key]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer

      # 3. File Format and Structure Checks
      - id: check-json
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.1
    hooks:
      - id: pylint

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint-fix
      - id: markdownlint
